@startuml monopoly

class Jugador {
    - identificador : String
    - nombre : String
    - saldo : double
    - posicionActual : int
    - activo : boolean

    + Jugador(identificador : String, nombre : String, saldo : double)
    + getIdentificador() : String
    + getNombre() : String
    + getSaldo() : double
    + getPosicionActual() : int
    + esActivo() : boolean
}

@enduml